# Generated by Django 5.2.11 on 2026-02-07 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_executivetenure'),
        ('finance', '0003_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='sender_id',
            field=models.CharField(max_length=50, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='sender_name',
            field=models.CharField(max_length=200, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense')], default='expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.member'),
        ),
    ]
