# Generated by Django 5.2.11 on 2026-02-07 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_executivetenure'),
        ('finance', '0004_income_sender_id_income_sender_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_incomes', to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='income',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes_recorded', to='accounts.member'),
        ),
    ]
