# Generated by Django 5.2.11 on 2026-02-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_executivetenure'),
        ('finance', '0005_income_member_alter_income_recorded_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('member', 'year')},
        ),
    ]
