# Generated by Django 5.2.11 on 2026-02-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('presented_by', models.CharField(max_length=200)),
                ('date_presented', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], max_length=20)),
                ('handled_by', models.CharField(choices=[('taskforce', 'Task Force'), ('executives', 'Executives')], max_length=20)),
            ],
        ),
    ]
