# Generated by Django 5.2.11 on 2026-02-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('executive', 'Executive'), ('floor', 'Floor Member')], max_length=20)),
                ('executive_position', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=20)),
                ('year_joined', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('President', 'President'), ('Deputy President', 'Deputy President'), ('Secretary', 'Secretary'), ('Assistant Secretary', 'Assistant Secretary'), ('Treasurer', 'Treasurer'), ('Financial Secretary', 'Financial Secretary'), ('Assistant Financial Secretary', 'Assistant Financial Secretary'), ('PRO', 'PRO'), ('Assistant PRO', 'Assistant PRO'), ('DOS', 'DOS'), ('Assistant DOS', 'Assistant DOS'), ('Provost 1', 'Provost 1'), ('Provost 2', 'Provost 2'), ('Provost 3', 'Provost 3'), ('Auditor 1', 'Auditor 1'), ('Auditor 2', 'Auditor 2')], max_length=100)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.member')),
            ],
        ),
    ]
