# Generated by Django 5.2.11 on 2026-02-07 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_executivetenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='executive',
            name='tenure',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='executives', to='accounts.executivetenure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='executive',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
        migrations.AlterUniqueTogether(
            name='executive',
            unique_together={('tenure', 'position')},
        ),
    ]
