# Generated by Django 5.2.11 on 2026-02-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_executive_tenure_alter_executive_member_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='executive',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='executive',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
        migrations.RemoveField(
            model_name='executive',
            name='tenure',
        ),
    ]
